dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
  - "8"
script:
  - yarn typecheck
  - yarn build
  - ./scripts/test-ci.sh
  - yarn prettier --list-different "{src,tests}/**/*.{js,ts}"
after_success:
  - ./scripts/analyze.sh
cache: yarn
notifications:
  email: false
  webhooks:
    - secure: "kIENwirW6kMeclDO71Ov4e9hpsSHd6U6ZiMBbSg48l6Pkat1Xjwzp/Gk32buNVGyDK9l/kIXBLwtHBovu49cKCd6NkckW7Jyl5iyEmi2kPg+ue8hQU+X+81if3qX/iJGxDpe3UUd8M4JSqDHvSVc+SO2eKZyN5/wN+w9fTJ/o4bMKKkZt2BRWehB71N7X2IYSdx5qSMxn0ldpxwP/NeueoG9+1kHRyjniKtKvsXvKBX96axfl3Xfu54XiuECEKHf7421V2TPgqEiaBvKZWjn2X2lTMU4OZ0jgthMNU1GaRJUxXPJJttJxvXyW+Sd79mgjjKeKsi7GHSGQukK015/8cvwWbDJvvVhwh/ALqMpDM3U5njLklZpv6D0pnpXcbhop5kxFQWtpim8NghaKMZ3Slk1K8kTwJs3hl854E4mSbiNSmTNV1SZIMxQD3IEwxTT+DLfChfkwCPt3eqTW6Q4Vqnk70PufxwQSjwvfI4v0DSRtAJT4TBD0ioN56rxOUvJbV+qbmj+65UWrMqRpbcJRETpDQ1rIP+neXHcXIWbSpVmXlrn5U7Hv3mZNCYwLUGl0qq6gbwBiW4itb09k+DIpJDMkIcQBu1WrL3IuWVSuq98scTPyXTi5tzrXj532bEIftxpbZUJHN/Y2C73eBeD705agxzxdiwci/gX/wvSMvY="
  on_start: always
addons:
  sonarcloud:
    organization: "sonarsource"
    token:
      secure: "MOya+pLm6SN59G7zwSl+F8LKTIs2wW9H0KI0tBElzIaiu7gpMZt+43b9wCDSs53KKeSEIAnlCKYEvgBi+tzbqNkA51GGbaHchUtYZOXIZQjgJahue3n243DhTLxxF0H9ZMrXptOJ1IWHahpyqIPz1LnZR97CQkVjeVvFNpexJxXj8nmTwDVOy50ATbZSXijYS3A+46VcETg+iRXa01TNtXJs48FRS7ZBKrfIEUGwlQkN95jNov4THbCH4CM8CXmwSq3bCdYRCkJoJPzMrg2DILJse9hYBpx/BPB7XLDw+c/+GEy0/M/kTV7nAlMfJeX2eSTekqS5i3qXmltXF6bgTo8lgcyPgTMPCvbKKrcUtCVlUxe4AmFx6iFWm19dzCobRjVAIjJfQb6vLBWuJR1Dp7xC+cdiI2TVdKyR6KMceXbakmpsdTREPt+qMhrif50VqqrdUC2pzDyuArOzA3s0moVz3UrOFzmHa04FAlnOM7J0nFY0rsGFswTPDjDK0emL2kQ/yYjLJkPtu+YOfeHlU1iuFO6oaqAe1SZI6H/T1idoNQCTqMABqP4tmSKmqebYTe9m4jNz7wk4ArWv4LxRHYKZFYuqlGrFkLB4vBm+HNlgS4UHPse28+/5bL0EkJjxLGCyZ4Iyt+LVUWqScQh1Jpg7/ZTnPwQszBKeE5ojFRE="
